kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager
  namespace: mon
data:
  config.yml: |-
    global:
      resolve_timeout: 5m
      slack_api_url: 'https://hooks.slack.com/services/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'

    templates:
    - '/etc/alertmanager-templates/*.tmpl'
    route:
      group_by: ['alertname', 'cluster', 'service']
      group_wait: 10s
      group_interval: 1m
      repeat_interval: 5m
      receiver: default
      routes:
      - match:
          team: devops
        receiver: devops
        continue: true
      - match:
          team: dev
        receiver: dev
        continue: true

    receivers:
    - name: 'default'

# operator specific metrics
    - name: 'devops'
      slack_configs:
      - channel: '#k8-alerts'
        send_resolved: true

# developer specific metrics
    - name: 'dev'
      slack_configs:
      - channel: '#k8-alerts'
        send_resolved: true


