apiVersion: v1
kind: Namespace
metadata:
  name: mon
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mon
  namespace: mon
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: mon
subjects:
  - kind: ServiceAccount
    name: mon
    namespace: mon
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
