expose:
  clusterIP:
    name: harbor
    ports:
      httpPort: 80
      httpsPort: 443
      notaryPort: 4443

externalURL: expose.clusterIP.name

persistence:
  enabled: true
  resourcePolicy: 
  persistentVolumeClaim:
    registry:
      existingClaim: ""
      storageClass: ""
      subPath: ""
      accessMode: ReadWriteOnce
      size: 5Gi
    chartmuseum:
      existingClaim: ""
      storageClass: ""
      subPath: ""
      accessMode: ReadWriteOnce
      size: 5Gi
    jobservice:
      existingClaim: ""
      storageClass: ""
      subPath: ""
      accessMode: ReadWriteOnce
      size: 1Gi
  imageChartStorage:
    disableredirect: false
    type: gcs
    gcs:
      bucket: bucketname
      # The base64 encoded json file which contains the key
      encodedkey: base64-encoded-json-key-file

imagePullPolicy: IfNotPresent

imagePullSecrets:

logLevel: info
harborAdminPassword: "Harbor12345"
secretKey: "not-a-secure-key"

proxy:
  httpProxy:
  httpsProxy:
  noProxy: 127.0.0.1,localhost,.local,.internal
  components:
    - core
    - jobservice
    - clair

nginx:
  image:
    repository: goharbor/nginx-photon
    tag: dev
  replicas: 1
  nodeSelector: {}
  tolerations: []
  affinity: {}
  podAnnotations: {}

portal:
  image:
    repository: goharbor/harbor-portal
    tag: dev
  replicas: 1
  nodeSelector: {}
  tolerations: []
  affinity: {}
  resources:
    requests:
      memory: 256Mi
      cpu: 100m  
  podAnnotations: {}

core:
  image:
    repository: goharbor/harbor-core
    tag: dev
  replicas: 1
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
  nodeSelector: {}
  tolerations: []
  affinity: {}
  podAnnotations: {}
  secret: "vWLVrV2egEncx2Bj"
  secretName: ""

jobservice:
  image:
    repository: goharbor/harbor-jobservice
    tag: dev
  replicas: 1
  maxJobWorkers: 10
  jobLogger: file
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
  nodeSelector: {}
  tolerations: []
  affinity: {}
  podAnnotations: {}
  secret: "vWLVrV2egEncx2Bj"

registry:
  registry:
    image:
      repository: goharbor/registry-photon
      tag: dev
  controller:
    image:
      repository: goharbor/harbor-registryctl
      tag: dev
  replicas: 1
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
  nodeSelector: {}
  tolerations: []
  affinity: {}
  podAnnotations: {}
  secret: "vWLVrV2egEncx2Bj"

chartmuseum:
  enabled: true
  absoluteUrl: false
  image:
    repository: goharbor/chartmuseum-photon
    tag: dev
  replicas: 1
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
  nodeSelector: {}
  tolerations: []
  affinity: {}
  podAnnotations: {}

clair:
  enabled: true
  image:
    repository: goharbor/clair-photon
    tag: dev
  replicas: 1
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
  updatersInterval: 12
  nodeSelector: {}
  tolerations: []
  affinity: {}
  podAnnotations: {}

notary:
  enabled: true
  server:
    image:
      repository: goharbor/notary-server-photon
      tag: dev
    replicas: 1
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
  signer:
    image:
      repository: goharbor/notary-signer-photon
      tag: dev
    replicas: 1
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
  nodeSelector: {}
  tolerations: []
  affinity: {}
  podAnnotations: {}
  secretName: ""

database:
  type: internal
  internal:
    image:
      repository: goharbor/harbor-db
      tag: dev
    password: "BUF6eQ7afbjyfc2D"
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
    nodeSelector: {}
    tolerations: []
    affinity: {}
  maxIdleConns: 50
  maxOpenConns: 100
  podAnnotations: {}

redis:
  type: internal
  internal:
    image:
      repository: goharbor/redis-photon
      tag: dev
      resources:
        requests:
          memory: 256Mi
          cpu: 100m
    nodeSelector: {}
    tolerations: []
    affinity: {}